from setuptools import setup

# Auto-generated by SdkCodeGenerator — do not edit manually
setup(
    name="iris-client-sdk",
    version="0.1.0",
    description="Auto-generated Python client for the Iris MCP server",
    packages=["iris_sdk"],
    install_requires=["requests>=2.31.0", "pydantic>=2.0.0"],
    python_requires=">=3.9",
)
