packages:
  - 'apps/*'
  - 'packages/*'
  - 'packages/connectors/*'
allowBuilds:
  '@clerk/shared': set this to true or false
  esbuild: set this to true or false
  msw: set this to true or false
onlyBuiltDependencies:
  - '@clerk/shared'
  - esbuild
  - msw
