import { ok, err, type Result } from 'neverthrow';
import { z } from 'zod';
import { logger } from '@iris/core/logger';

const log = logger.child({ service: 'mcp-tool-generator' });

type SqlFn = (strings: TemplateStringsArray, ...values: unknown[]) => Promise<unknown[]>;

export type ConnectorEntityField = {
  name: string;
  type: 'string' | 'number' | 'boolean' | 'date' | 'array' | 'object';
  required?: boolean;
  description?: string;
  pii?: boolean;
};

export type ConnectorEntitySchema = {
  entityType: string;
  fields: ConnectorEntityField[];
  description?: string;
};

export type ConnectorSchema = {
  connectorId: string;
  connectorName: string;
  entities: ConnectorEntitySchema[];
};

export type AutoGeneratedTool = {
  toolId: string;
  workspaceId: string;
  sourceConnectorId: string;
  entityType: string;
  toolDefinition: McpToolDefinition;
  version: number;
  generatedAt: Date;
  lastInvokedAt: Date | null;
};

export type McpToolDefinition = {
  name: string;
  description: string;
  inputSchema: z.ZodTypeAny;
  inputSchemaJson: Record<string, unknown>;
};

export type ToolVersionRecord = {
  toolId: string;
  version: number;
  schemaChanges: string[];
  isBackwardCompatible: boolean;
  deprecationWarning: string | null;
};

export type ToolValidationResult = {
  valid: boolean;
  toolId: string;
  errors: string[];
  parsedInput: Record<string, unknown> | null;
};

/**
 * Build a Zod input schema from a connector entity schema.
 * @param entitySchema - Source entity schema from connector
 * @param toolType - Whether this is a query or list-metrics tool
 */
export function buildToolInputSchema(
  entitySchema: ConnectorEntitySchema,
  toolType: 'query' | 'list-metrics',
): { zodSchema: z.ZodTypeAny; jsonSchema: Record<string, unknown> } {
  const shape: Record<string, z.ZodTypeAny> = {};
  const jsonProperties: Record<string, unknown> = {};
  const required: string[] = [];

  if (toolType === 'query') {
    shape['query'] = z.string().min(1).describe('Natural language search query');
    shape['limit'] = z.number().int().min(1).max(100).optional().describe('Max results to return');
    shape['contextBudget'] = z.number().int().min(100).max(8000).optional().describe('Token budget for response');
    jsonProperties['query'] = { type: 'string', description: 'Natural language search query' };
    jsonProperties['limit'] = { type: 'integer', minimum: 1, maximum: 100 };
    jsonProperties['contextBudget'] = { type: 'integer', minimum: 100, maximum: 8000 };
    required.push('query');
  } else {
    shape['entityId'] = z.string().min(1).describe('Entity ID to fetch metrics for');
    shape['metricNames'] = z.array(z.string()).optional().describe('Specific metric names to fetch');
    shape['since'] = z.string().datetime().optional().describe('Start date for metrics (ISO 8601)');
    jsonProperties['entityId'] = { type: 'string', description: 'Entity ID to fetch metrics for' };
    jsonProperties['metricNames'] = { type: 'array', items: { type: 'string' } };
    jsonProperties['since'] = { type: 'string', format: 'date-time' };
    required.push('entityId');
  }

  // Add filterable non-PII fields as optional filter parameters
  for (const field of entitySchema.fields) {
    if (field.pii) continue;
    if (field.type === 'string' || field.type === 'number' || field.type === 'boolean') {
      const filterKey = `filter_${field.name}`;
      switch (field.type) {
        case 'string':
          shape[filterKey] = z.string().optional().describe(`Filter by ${field.name}`);
          jsonProperties[filterKey] = { type: 'string', description: `Filter by ${field.name}` };
          break;
        case 'number':
          shape[filterKey] = z.number().optional().describe(`Filter by ${field.name}`);
          jsonProperties[filterKey] = { type: 'number', description: `Filter by ${field.name}` };
          break;
        case 'boolean':
          shape[filterKey] = z.boolean().optional().describe(`Filter by ${field.name}`);
          jsonProperties[filterKey] = { type: 'boolean', description: `Filter by ${field.name}` };
          break;
      }
    }
  }

  return {
    zodSchema: z.object(shape),
    jsonSchema: { type: 'object', properties: jsonProperties, required },
  };
}

/**
 * Generate MCP tool definitions from a connector schema.
 * @param connectorSchema - Connector entity schema to generate tools from
 * @param workspaceId - Target workspace
 */
export function generateToolsFromConnectorSchema(
  connectorSchema: ConnectorSchema,
  workspaceId: string,
): AutoGeneratedTool[] {
  const tools: AutoGeneratedTool[] = [];
  const now = new Date();

  for (const entity of connectorSchema.entities) {
    const connId = connectorSchema.connectorId;
    const entityType = entity.entityType.toLowerCase();

    // Query tool: query-<connector>-<entity>
    const queryToolId = `query-${connId}-${entityType}`;
    const { zodSchema: querySchema, jsonSchema: queryJson } = buildToolInputSchema(entity, 'query');
    tools.push({
      toolId: queryToolId,
      workspaceId,
      sourceConnectorId: connId,
      entityType,
      version: 1,
      generatedAt: now,
      lastInvokedAt: null,
      toolDefinition: {
        name: queryToolId,
        description: `Search ${connectorSchema.connectorName} ${entity.entityType}s. ${entity.description ?? ''}`.trim(),
        inputSchema: querySchema,
        inputSchemaJson: queryJson,
      },
    });

    // Metrics tool: list-<connector>-<entity>-metrics
    const metricsToolId = `list-${connId}-${entityType}-metrics`;
    const { zodSchema: metricsSchema, jsonSchema: metricsJson } = buildToolInputSchema(entity, 'list-metrics');
    tools.push({
      toolId: metricsToolId,
      workspaceId,
      sourceConnectorId: connId,
      entityType,
      version: 1,
      generatedAt: now,
      lastInvokedAt: null,
      toolDefinition: {
        name: metricsToolId,
        description: `Fetch metrics for a ${connectorSchema.connectorName} ${entity.entityType}.`,
        inputSchema: metricsSchema,
        inputSchemaJson: metricsJson,
      },
    });
  }

  log.info('Tools generated from connector schema', {
    connectorId: connectorSchema.connectorId,
    toolCount: tools.length,
    entityCount: connectorSchema.entities.length,
  });

  return tools;
}

/**
 * Compute schema changes between two tool versions and whether they are backward compatible.
 * @param oldSchema - Previous JSON schema
 * @param newSchema - New JSON schema
 */
export function versionToolDefinition(
  oldSchema: Record<string, unknown>,
  newSchema: Record<string, unknown>,
): ToolVersionRecord {
  const changes: string[] = [];
  let isBackwardCompatible = true;

  const oldProps = (oldSchema['properties'] as Record<string, unknown>) ?? {};
  const newProps = (newSchema['properties'] as Record<string, unknown>) ?? {};
  const oldRequired = new Set<string>((oldSchema['required'] as string[]) ?? []);
  const newRequired = new Set<string>((newSchema['required'] as string[]) ?? []);

  // Detect removed fields (breaking)
  for (const key of Object.keys(oldProps)) {
    if (!(key in newProps)) {
      changes.push(`removed field: ${key}`);
      isBackwardCompatible = false;
    }
  }

  // Detect newly required fields (breaking for existing callers)
  for (const key of newRequired) {
    if (!oldRequired.has(key) && !(key in oldProps)) {
      changes.push(`new required field: ${key}`);
      isBackwardCompatible = false;
    }
  }

  // Detect added optional fields (non-breaking)
  for (const key of Object.keys(newProps)) {
    if (!(key in oldProps)) {
      changes.push(`added optional field: ${key}`);
    }
  }

  return {
    toolId: '',
    version: 0,
    schemaChanges: changes,
    isBackwardCompatible,
    deprecationWarning: isBackwardCompatible
      ? null
      : 'Breaking schema change — update tool callers before upgrading.',
  };
}

/**
 * Validate an incoming tool invocation input against the tool's schema.
 * @param tool - Auto-generated tool
 * @param rawInput - Raw JSON input from caller
 */
export function validateToolUsage(
  tool: AutoGeneratedTool,
  rawInput: unknown,
): ToolValidationResult {
  const result = tool.toolDefinition.inputSchema.safeParse(rawInput);
  if (result.success) {
    return { valid: true, toolId: tool.toolId, errors: [], parsedInput: result.data as Record<string, unknown> };
  }
  return {
    valid: false,
    toolId: tool.toolId,
    errors: result.error.issues.map(i => `${i.path.join('.')}: ${i.message}`),
    parsedInput: null,
  };
}

/**
 * Persist auto-generated tools to the DB.
 * @param sql - SQL function
 * @param tools - Tools to upsert
 */
export async function persistAutoGeneratedTools(
  sql: SqlFn,
  tools: AutoGeneratedTool[],
): Promise<Result<void, Error>> {
  try {
    for (const t of tools) {
      await sql`
        INSERT INTO auto_generated_tools (
          workspace_id, tool_id, source_connector_id, entity_type,
          tool_definition_json, version, generated_at, last_invoked_at
        ) VALUES (
          ${t.workspaceId}, ${t.toolId}, ${t.sourceConnectorId}, ${t.entityType},
          ${JSON.stringify(t.toolDefinition.inputSchemaJson)}, ${t.version},
          ${t.generatedAt}, ${t.lastInvokedAt}
        )
        ON CONFLICT (workspace_id, tool_id) DO UPDATE SET
          tool_definition_json = EXCLUDED.tool_definition_json,
          version = auto_generated_tools.version + 1,
          generated_at = EXCLUDED.generated_at
      `;
    }
    return ok(undefined);
  } catch (e) {
    return err(e instanceof Error ? e : new Error(String(e)));
  }
}

/**
 * List all auto-generated tools for a workspace.
 * @param sql - SQL function
 * @param workspaceId - Target workspace
 */
export async function listAutoGeneratedTools(
  sql: SqlFn,
  workspaceId: string,
): Promise<Result<Omit<AutoGeneratedTool, 'toolDefinition'>[], Error>> {
  try {
    const rows = await sql`
      SELECT tool_id, workspace_id, source_connector_id, entity_type,
             version, generated_at, last_invoked_at
      FROM auto_generated_tools
      WHERE workspace_id = ${workspaceId}
      ORDER BY source_connector_id, entity_type, tool_id
    ` as unknown as Array<{
      tool_id: string;
      workspace_id: string;
      source_connector_id: string;
      entity_type: string;
      version: number;
      generated_at: string;
      last_invoked_at: string | null;
    }>;

    return ok(rows.map(r => ({
      toolId: r.tool_id,
      workspaceId: r.workspace_id,
      sourceConnectorId: r.source_connector_id,
      entityType: r.entity_type,
      version: r.version,
      generatedAt: new Date(r.generated_at),
      lastInvokedAt: r.last_invoked_at ? new Date(r.last_invoked_at) : null,
    })));
  } catch (e) {
    return err(e instanceof Error ? e : new Error(String(e)));
  }
}

/**
 * Record tool invocation timestamp.
 * @param sql - SQL function
 * @param workspaceId - Workspace context
 * @param toolId - Tool that was invoked
 */
export async function recordToolInvocation(
  sql: SqlFn,
  workspaceId: string,
  toolId: string,
): Promise<Result<void, Error>> {
  try {
    await sql`
      UPDATE auto_generated_tools
      SET last_invoked_at = NOW()
      WHERE workspace_id = ${workspaceId} AND tool_id = ${toolId}
    `;
    return ok(undefined);
  } catch (e) {
    return err(e instanceof Error ? e : new Error(String(e)));
  }
}
