import { describe, it, expect, vi } from 'vitest';
import { Hono } from 'hono';

vi.mock('@iris/semantic-core/mcp-tool-generator', () => ({
  listAutoGeneratedTools: vi.fn(async () => ({
    isOk: () => true,
    isErr: () => false,
    value: [
      {
        toolId: 'query-hubspot-contact',
        workspaceId: 'ws1',
        sourceConnectorId: 'hubspot',
        entityType: 'contact',
        version: 1,
        generatedAt: new Date('2026-06-08T00:00:00Z'),
        lastInvokedAt: null,
      },
    ],
  })),
  generateToolsFromConnectorSchema: vi.fn((_schema: unknown, _wsId: string) => [
    {
      toolId: 'query-hubspot-contact',
      workspaceId: 'ws1',
      sourceConnectorId: 'hubspot',
      entityType: 'contact',
      version: 1,
      generatedAt: new Date(),
      lastInvokedAt: null,
      toolDefinition: {
        name: 'query-hubspot-contact',
        description: 'Search HubSpot contacts',
        inputSchema: { safeParse: (v: unknown) => {
          const obj = v as Record<string, unknown>;
          if (!obj?.['query']) return { success: false, error: { issues: [{ path: ['query'], message: 'required' }] } };
          return { success: true, data: v };
        }},
        inputSchemaJson: { type: 'object', properties: { query: { type: 'string' } }, required: ['query'] },
      },
    },
  ]),
  validateToolUsage: vi.fn((_tool: unknown, input: unknown) => {
    const obj = input as Record<string, unknown> | undefined;
    if (!obj || !obj['query']) {
      return { valid: false, toolId: 'query-hubspot-contact', errors: ['query: required'], parsedInput: null };
    }
    return { valid: true, toolId: 'query-hubspot-contact', errors: [], parsedInput: obj };
  }),
  persistAutoGeneratedTools: vi.fn(async () => ({ isOk: () => true, isErr: () => false })),
  recordToolInvocation: vi.fn(async () => ({ isOk: () => true, isErr: () => false })),
  versionToolDefinition: vi.fn((_old: unknown, _new: unknown) => ({
    toolId: '',
    version: 0,
    schemaChanges: ['added optional field: limit'],
    isBackwardCompatible: true,
    deprecationWarning: null,
  })),
}));

vi.mock('@iris/core/logger', () => ({
  logger: { child: () => ({ info: vi.fn(), error: vi.fn(), warn: vi.fn() }) },
}));

import { createMcpAutoToolsRoutes } from '../routes/mcp-auto-tools';

const mockSql = {} as never;

function buildApp() {
  const app = new Hono();
  app.route('/mcp/auto-tools', createMcpAutoToolsRoutes(mockSql));
  return app;
}

describe('GET /mcp/auto-tools', () => {
  it('returns tool list with meta count', async () => {
    const res = await buildApp().request('/mcp/auto-tools', {
      headers: { 'x-workspace-id': 'ws1' },
    });
    expect(res.status).toBe(200);
    const body = await res.json() as { data: Array<{ toolId: string }>; meta: { count: number } };
    expect(body.data).toHaveLength(1);
    expect(body.data[0]!.toolId).toBe('query-hubspot-contact');
    expect(body.meta.count).toBe(1);
  });
});

describe('POST /mcp/auto-tools/generate', () => {
  const validPayload = {
    connectorId: 'hubspot',
    connectorName: 'HubSpot',
    entities: [
      {
        entityType: 'contact',
        fields: [{ name: 'company', type: 'string' }],
      },
    ],
  };

  it('returns 201 with generated tool stubs', async () => {
    const res = await buildApp().request('/mcp/auto-tools/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(validPayload),
    });
    expect(res.status).toBe(201);
    const body = await res.json() as { data: Array<{ toolId: string }> };
    expect(body.data.length).toBeGreaterThan(0);
  });

  it('returns 400 for missing connectorId', async () => {
    const res = await buildApp().request('/mcp/auto-tools/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ connectorName: 'X', entities: [] }),
    });
    expect(res.status).toBe(400);
  });
});

describe('GET /mcp/auto-tools/:toolId/schema', () => {
  it('returns tool schema info for known tool', async () => {
    const res = await buildApp().request('/mcp/auto-tools/query-hubspot-contact/schema', {
      headers: { 'x-workspace-id': 'ws1' },
    });
    expect(res.status).toBe(200);
    const body = await res.json() as { data: { toolId: string; version: number } };
    expect(body.data.toolId).toBe('query-hubspot-contact');
  });

  it('returns 404 for unknown tool', async () => {
    const res = await buildApp().request('/mcp/auto-tools/unknown-tool/schema', {
      headers: { 'x-workspace-id': 'ws1' },
    });
    expect(res.status).toBe(404);
  });
});

describe('POST /mcp/auto-tools/:toolId/test', () => {
  it('returns valid: true for correct input', async () => {
    const res = await buildApp().request('/mcp/auto-tools/query-hubspot-contact/test', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ input: { query: 'find contacts' } }),
    });
    expect(res.status).toBe(200);
    const body = await res.json() as { data: { valid: boolean } };
    expect(body.data.valid).toBe(true);
  });

  it('returns 400 when input field is missing from body', async () => {
    const res = await buildApp().request('/mcp/auto-tools/query-hubspot-contact/test', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({}),
    });
    expect(res.status).toBe(400);
  });
});

describe('POST /mcp/auto-tools/version', () => {
  it('returns compatibility result', async () => {
    const res = await buildApp().request('/mcp/auto-tools/version', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        oldSchema: { properties: { query: {} }, required: ['query'] },
        newSchema: { properties: { query: {}, limit: {} }, required: ['query'] },
      }),
    });
    expect(res.status).toBe(200);
    const body = await res.json() as { data: { isBackwardCompatible: boolean; schemaChanges: string[] } };
    expect(body.data.isBackwardCompatible).toBe(true);
    expect(body.data.schemaChanges).toContain('added optional field: limit');
  });

  it('returns 400 for missing schemas', async () => {
    const res = await buildApp().request('/mcp/auto-tools/version', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ oldSchema: {} }),
    });
    expect(res.status).toBe(400);
  });
});
