import { describe, it, expect, vi } from 'vitest';
import {
  buildToolInputSchema,
  generateToolsFromConnectorSchema,
  versionToolDefinition,
  validateToolUsage,
  persistAutoGeneratedTools,
  listAutoGeneratedTools,
  recordToolInvocation,
} from '../mcp-tool-generator';
import type { ConnectorSchema, AutoGeneratedTool } from '../mcp-tool-generator';

type Sql = Parameters<typeof persistAutoGeneratedTools>[0];

const SAMPLE_SCHEMA: ConnectorSchema = {
  connectorId: 'hubspot',
  connectorName: 'HubSpot',
  entities: [
    {
      entityType: 'contact',
      description: 'CRM contacts',
      fields: [
        { name: 'email', type: 'string', pii: true },
        { name: 'company', type: 'string' },
        { name: 'stage', type: 'string' },
        { name: 'deal_count', type: 'number' },
        { name: 'is_active', type: 'boolean' },
      ],
    },
    {
      entityType: 'deal',
      fields: [
        { name: 'amount', type: 'number' },
        { name: 'stage', type: 'string' },
        { name: 'owner', type: 'string' },
      ],
    },
  ],
};

describe('buildToolInputSchema', () => {
  it('query tool includes required "query" field', () => {
    const { zodSchema, jsonSchema } = buildToolInputSchema(SAMPLE_SCHEMA.entities[0]!, 'query');
    const result = zodSchema.safeParse({ query: 'find contacts' });
    expect(result.success).toBe(true);
    expect((jsonSchema['required'] as string[])).toContain('query');
  });

  it('query tool accepts optional limit and contextBudget', () => {
    const { zodSchema } = buildToolInputSchema(SAMPLE_SCHEMA.entities[0]!, 'query');
    const result = zodSchema.safeParse({ query: 'test', limit: 10, contextBudget: 2000 });
    expect(result.success).toBe(true);
  });

  it('query tool rejects empty query string', () => {
    const { zodSchema } = buildToolInputSchema(SAMPLE_SCHEMA.entities[0]!, 'query');
    const result = zodSchema.safeParse({ query: '' });
    expect(result.success).toBe(false);
  });

  it('list-metrics tool includes required "entityId" field', () => {
    const { zodSchema, jsonSchema } = buildToolInputSchema(SAMPLE_SCHEMA.entities[0]!, 'list-metrics');
    const result = zodSchema.safeParse({ entityId: 'hubspot:contact:1' });
    expect(result.success).toBe(true);
    expect((jsonSchema['required'] as string[])).toContain('entityId');
  });

  it('excludes PII fields from filter parameters', () => {
    const { jsonSchema } = buildToolInputSchema(SAMPLE_SCHEMA.entities[0]!, 'query');
    expect(jsonSchema['properties']).not.toHaveProperty('filter_email');
  });

  it('includes non-PII fields as optional filters', () => {
    const { jsonSchema } = buildToolInputSchema(SAMPLE_SCHEMA.entities[0]!, 'query');
    const props = jsonSchema['properties'] as Record<string, unknown>;
    expect(props).toHaveProperty('filter_company');
    expect(props).toHaveProperty('filter_deal_count');
    expect(props).toHaveProperty('filter_is_active');
  });
});

describe('generateToolsFromConnectorSchema', () => {
  it('generates 2 tools per entity (query + list-metrics)', () => {
    const tools = generateToolsFromConnectorSchema(SAMPLE_SCHEMA, 'ws1');
    expect(tools).toHaveLength(4); // 2 entities × 2 tools
  });

  it('uses correct tool naming convention', () => {
    const tools = generateToolsFromConnectorSchema(SAMPLE_SCHEMA, 'ws1');
    const ids = tools.map(t => t.toolId);
    expect(ids).toContain('query-hubspot-contact');
    expect(ids).toContain('list-hubspot-contact-metrics');
    expect(ids).toContain('query-hubspot-deal');
    expect(ids).toContain('list-hubspot-deal-metrics');
  });

  it('sets correct sourceConnectorId', () => {
    const tools = generateToolsFromConnectorSchema(SAMPLE_SCHEMA, 'ws1');
    for (const t of tools) expect(t.sourceConnectorId).toBe('hubspot');
  });

  it('sets version 1 for all generated tools', () => {
    const tools = generateToolsFromConnectorSchema(SAMPLE_SCHEMA, 'ws1');
    for (const t of tools) expect(t.version).toBe(1);
  });

  it('sets lastInvokedAt to null for new tools', () => {
    const tools = generateToolsFromConnectorSchema(SAMPLE_SCHEMA, 'ws1');
    for (const t of tools) expect(t.lastInvokedAt).toBeNull();
  });

  it('returns empty array for connector with no entities', () => {
    const tools = generateToolsFromConnectorSchema({ connectorId: 'empty', connectorName: 'Empty', entities: [] }, 'ws1');
    expect(tools).toHaveLength(0);
  });
});

describe('versionToolDefinition', () => {
  it('detects added optional field as backward compatible', () => {
    const oldSchema = { properties: { query: {} }, required: ['query'] };
    const newSchema = { properties: { query: {}, limit: {} }, required: ['query'] };
    const result = versionToolDefinition(oldSchema, newSchema);
    expect(result.isBackwardCompatible).toBe(true);
    expect(result.schemaChanges).toContain('added optional field: limit');
  });

  it('detects removed field as breaking change', () => {
    const oldSchema = { properties: { query: {}, limit: {} }, required: ['query'] };
    const newSchema = { properties: { query: {} }, required: ['query'] };
    const result = versionToolDefinition(oldSchema, newSchema);
    expect(result.isBackwardCompatible).toBe(false);
    expect(result.deprecationWarning).not.toBeNull();
  });

  it('detects new required field as breaking change', () => {
    const oldSchema = { properties: { query: {} }, required: ['query'] };
    const newSchema = { properties: { query: {}, workspaceId: {} }, required: ['query', 'workspaceId'] };
    const result = versionToolDefinition(oldSchema, newSchema);
    expect(result.isBackwardCompatible).toBe(false);
  });

  it('returns no changes for identical schemas', () => {
    const schema = { properties: { query: {} }, required: ['query'] };
    const result = versionToolDefinition(schema, schema);
    expect(result.schemaChanges).toHaveLength(0);
    expect(result.isBackwardCompatible).toBe(true);
  });
});

describe('validateToolUsage', () => {
  function makeQueryTool(): AutoGeneratedTool {
    const tools = generateToolsFromConnectorSchema(SAMPLE_SCHEMA, 'ws1');
    return tools.find(t => t.toolId === 'query-hubspot-contact')!;
  }

  it('returns valid: true for correct input', () => {
    const tool = makeQueryTool();
    const result = validateToolUsage(tool, { query: 'find contacts named John' });
    expect(result.valid).toBe(true);
    expect(result.parsedInput).toHaveProperty('query', 'find contacts named John');
  });

  it('returns valid: false for missing required field', () => {
    const tool = makeQueryTool();
    const result = validateToolUsage(tool, { limit: 5 });
    expect(result.valid).toBe(false);
    expect(result.errors.length).toBeGreaterThan(0);
  });

  it('returns valid: false for wrong type', () => {
    const tool = makeQueryTool();
    const result = validateToolUsage(tool, { query: 42 });
    expect(result.valid).toBe(false);
  });
});

describe('persistAutoGeneratedTools', () => {
  it('calls sql once per tool and returns Ok', async () => {
    const sql = vi.fn().mockResolvedValue([]);
    const tools = generateToolsFromConnectorSchema(SAMPLE_SCHEMA, 'ws1');
    const result = await persistAutoGeneratedTools(sql as unknown as Sql, tools);
    expect(result.isOk()).toBe(true);
    expect(sql).toHaveBeenCalledTimes(tools.length);
  });

  it('returns Err when DB throws', async () => {
    const sql = vi.fn().mockRejectedValue(new Error('db error'));
    const tools = generateToolsFromConnectorSchema(SAMPLE_SCHEMA, 'ws1');
    const result = await persistAutoGeneratedTools(sql as unknown as Sql, tools);
    expect(result.isErr()).toBe(true);
  });
});

describe('listAutoGeneratedTools', () => {
  it('returns mapped tool list', async () => {
    const sql = vi.fn().mockResolvedValue([
      {
        tool_id: 'query-hubspot-contact',
        workspace_id: 'ws1',
        source_connector_id: 'hubspot',
        entity_type: 'contact',
        version: 1,
        generated_at: '2026-06-08T00:00:00Z',
        last_invoked_at: null,
      },
    ]);
    const result = await listAutoGeneratedTools(sql as unknown as Sql, 'ws1');
    expect(result.isOk()).toBe(true);
    if (result.isOk()) {
      expect(result.value[0]!.toolId).toBe('query-hubspot-contact');
      expect(result.value[0]!.lastInvokedAt).toBeNull();
    }
  });

  it('returns Err when DB throws', async () => {
    const sql = vi.fn().mockRejectedValue(new Error('db error'));
    const result = await listAutoGeneratedTools(sql as unknown as Sql, 'ws1');
    expect(result.isErr()).toBe(true);
  });
});

describe('recordToolInvocation', () => {
  it('executes UPDATE and returns Ok', async () => {
    const sql = vi.fn().mockResolvedValue([]);
    const result = await recordToolInvocation(sql as unknown as Sql, 'ws1', 'query-hubspot-contact');
    expect(result.isOk()).toBe(true);
    expect(sql).toHaveBeenCalledOnce();
  });

  it('returns Err when DB throws', async () => {
    const sql = vi.fn().mockRejectedValue(new Error('db error'));
    const result = await recordToolInvocation(sql as unknown as Sql, 'ws1', 'query-hubspot-contact');
    expect(result.isErr()).toBe(true);
  });
});
