import { Hono } from 'hono';
import { z } from 'zod';
import {
  listAutoGeneratedTools,
  generateToolsFromConnectorSchema,
  validateToolUsage,
  persistAutoGeneratedTools,
  recordToolInvocation,
  versionToolDefinition,
} from '@iris/semantic-core/mcp-tool-generator';
import type { ConnectorSchema } from '@iris/semantic-core/mcp-tool-generator';
import { logger } from '@iris/core/logger';

const log = logger.child({ route: 'mcp-auto-tools' });

type Sql = Parameters<typeof listAutoGeneratedTools>[0];
type SqlBindings = { sql: Sql };

const app = new Hono<{ Bindings: SqlBindings }>();

function getSql(c: { env: unknown }) {
  return (c.env as SqlBindings | undefined)?.sql;
}

const GenerateSchema = z.object({
  connectorId: z.string().min(1),
  connectorName: z.string().min(1),
  entities: z.array(z.object({
    entityType: z.string().min(1),
    description: z.string().optional(),
    fields: z.array(z.object({
      name: z.string().min(1),
      type: z.enum(['string', 'number', 'boolean', 'date', 'array', 'object']),
      required: z.boolean().optional(),
      description: z.string().optional(),
      pii: z.boolean().optional(),
    })),
  })),
});

const TestToolSchema = z.object({
  input: z.unknown().refine(v => v !== undefined, { message: 'input is required' }),
});

const VersionSchema = z.object({
  oldSchema: z.record(z.unknown()),
  newSchema: z.record(z.unknown()),
});

/** GET /mcp/auto-tools — list all auto-generated tools for workspace */
app.get('/', async (c) => {
  const workspaceId = c.req.header('x-workspace-id') ?? 'default';
  const sql = getSql(c);
  const result = await listAutoGeneratedTools(sql!, workspaceId);

  if (result.isErr()) {
    log.error('Failed to list auto-generated tools', { error: result.error.message });
    return c.json({ error: { code: 'DB_ERROR', message: 'Failed to load tools' } }, 500);
  }

  return c.json({ data: result.value, meta: { count: result.value.length } });
});

/** POST /mcp/auto-tools/generate — generate tools from connector schema */
app.post('/generate', async (c) => {
  const body = await c.req.json().catch(() => ({}));
  const parsed = GenerateSchema.safeParse(body);
  if (!parsed.success) {
    return c.json({ error: { code: 'VALIDATION_ERROR', message: 'Invalid connector schema', details: parsed.error.format() } }, 400);
  }

  const workspaceId = c.req.header('x-workspace-id') ?? 'default';
  const connectorSchema = parsed.data as unknown as ConnectorSchema;
  const tools = generateToolsFromConnectorSchema(connectorSchema, workspaceId);

  const sql = getSql(c);
  if (sql) {
    await persistAutoGeneratedTools(sql, tools).catch(e =>
      log.warn('Failed to persist generated tools', { error: (e as Error).message }),
    );
  }

  return c.json({ data: tools.map(t => ({ toolId: t.toolId, entityType: t.entityType, version: t.version })) }, 201);
});

/** GET /mcp/auto-tools/:toolId/schema — get the JSON schema for a tool */
app.get('/:toolId/schema', async (c) => {
  const workspaceId = c.req.header('x-workspace-id') ?? 'default';
  const toolId = c.req.param('toolId');

  const sql = getSql(c);
  const allResult = await listAutoGeneratedTools(sql!, workspaceId);

  if (allResult.isErr()) {
    return c.json({ error: { code: 'DB_ERROR', message: 'Failed to load tools' } }, 500);
  }

  const tool = allResult.value.find(t => t.toolId === toolId);
  if (!tool) {
    return c.json({ error: { code: 'NOT_FOUND', message: 'Tool not found' } }, 404);
  }

  return c.json({ data: { toolId, version: tool.version, generatedAt: tool.generatedAt } });
});

/** POST /mcp/auto-tools/:toolId/test — dry-run a tool with sample input */
app.post('/:toolId/test', async (c) => {
  const workspaceId = c.req.header('x-workspace-id') ?? 'default';
  const toolId = c.req.param('toolId');

  const body = await c.req.json().catch(() => ({}));
  const parsed = TestToolSchema.safeParse(body);
  if (!parsed.success) {
    return c.json({ error: { code: 'VALIDATION_ERROR', message: 'Missing input field' } }, 400);
  }

  // Re-generate a generic schema for validation (in production, loaded from DB)
  const sampleSchema: ConnectorSchema = {
    connectorId: toolId.split('-')[1] ?? 'unknown',
    connectorName: toolId.split('-')[1] ?? 'Unknown',
    entities: [{ entityType: toolId.split('-').slice(2).join('_') ?? 'entity', fields: [] }],
  };
  const tools = generateToolsFromConnectorSchema(sampleSchema, workspaceId);
  const tool = tools[0];

  if (!tool) {
    return c.json({ error: { code: 'NOT_FOUND', message: 'Tool not found' } }, 404);
  }

  const validation = validateToolUsage(tool, parsed.data.input);

  if (validation.valid && getSql(c)) {
    await recordToolInvocation(getSql(c)!, workspaceId, toolId).catch(() => undefined);
  }

  return c.json({ data: validation });
});

/** POST /mcp/auto-tools/version — check backward compatibility between schema versions */
app.post('/version', async (c) => {
  const body = await c.req.json().catch(() => ({}));
  const parsed = VersionSchema.safeParse(body);
  if (!parsed.success) {
    return c.json({ error: { code: 'VALIDATION_ERROR', message: 'oldSchema and newSchema required' } }, 400);
  }

  const result = versionToolDefinition(parsed.data.oldSchema, parsed.data.newSchema);
  return c.json({ data: result });
});

export default app;
