import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';

import { registerTool } from '../register-tool.js';

/**
 * Register dynamically generated connector tools with the MCP server.
 * Tools are loaded from the API at startup time via a local HTTP call.
 */

type AutoToolSpec = {
  toolId: string;
  sourceConnectorId: string;
  entityType: string;
  description: string;
  inputSchemaJson: Record<string, unknown>;
};

function buildZodSchemaFromJson(schemaJson: Record<string, unknown>): Record<string, z.ZodTypeAny> {
  const props = (schemaJson['properties'] as Record<string, { type?: string; description?: string }>) ?? {};
  const required = new Set<string>((schemaJson['required'] as string[]) ?? []);

  const shape: Record<string, z.ZodTypeAny> = {};

  for (const [key, def] of Object.entries(props)) {
    let field: z.ZodTypeAny;
    switch (def.type) {
      case 'integer':
      case 'number':
        field = z.number();
        break;
      case 'boolean':
        field = z.boolean();
        break;
      default:
        field = z.string();
    }
    if (def.description) field = field.describe(def.description);
    shape[key] = required.has(key) ? field : field.optional();
  }

  return shape;
}

/**
 * Register a set of auto-generated tools with the MCP server instance.
 * @param server - MCP server to register tools on
 * @param tools - Tool specs loaded from connector schemas
 * @param workspaceId - Workspace context for retrieval
 * @param retrievalBaseUrl - Base URL for context retrieval API
 */
export function registerAutoGeneratedTools(
  server: McpServer,
  tools: AutoToolSpec[],
  workspaceId: string,
  retrievalBaseUrl: string,
): void {
  for (const spec of tools) {
    const schema = buildZodSchemaFromJson(spec.inputSchemaJson);

    registerTool(
      server,
      spec.toolId,
      { description: spec.description, inputSchema: schema },
      async (input) => {
        const typedInput = input as Record<string, unknown>;
        const query = String(typedInput['query'] ?? typedInput['entityId'] ?? '');
        const limit = Number(typedInput['limit'] ?? 10);
        const contextBudget = Number(typedInput['contextBudget'] ?? 2000);

        try {
          const url = new URL(`${retrievalBaseUrl}/api/v1/entities`);
          url.searchParams.set('workspaceId', workspaceId);
          url.searchParams.set('connectorId', spec.sourceConnectorId);
          url.searchParams.set('entityType', spec.entityType);
          url.searchParams.set('query', query);
          url.searchParams.set('limit', String(limit));
          url.searchParams.set('contextBudget', String(contextBudget));

          const res = await fetch(url.toString(), {
            headers: { 'x-workspace-id': workspaceId },
            signal: AbortSignal.timeout(10_000),
          });

          if (!res.ok) {
            return {
              content: [{
                type: 'text' as const,
                text: JSON.stringify({ error: `Retrieval failed: HTTP ${res.status}` }),
              }],
            };
          }

          const data = await res.json() as { data: unknown };
          return {
            content: [{
              type: 'text' as const,
              text: JSON.stringify(data.data ?? []),
            }],
          };
        } catch (e) {
          return {
            content: [{
              type: 'text' as const,
              text: JSON.stringify({ error: e instanceof Error ? e.message : 'Retrieval failed' }),
            }],
          };
        }
      },
    );
  }
}

/**
 * Load auto-generated tool specs for a workspace from the API.
 * @param apiBaseUrl - Base URL for the Iris API
 * @param workspaceId - Workspace to load tools for
 */
export async function loadAutoGeneratedToolSpecs(
  apiBaseUrl: string,
  workspaceId: string,
): Promise<AutoToolSpec[]> {
  const res = await fetch(`${apiBaseUrl}/api/v1/mcp/auto-tools`, {
    headers: { 'x-workspace-id': workspaceId },
    signal: AbortSignal.timeout(10_000),
  });

  if (!res.ok) return [];

  const body = await res.json() as { data: Array<{
    toolId: string;
    sourceConnectorId: string;
    entityType: string;
  }> };

  return (body.data ?? []).map(t => ({
    toolId: t.toolId,
    sourceConnectorId: t.sourceConnectorId,
    entityType: t.entityType,
    description: `Auto-generated tool for ${t.sourceConnectorId} ${t.entityType} entities`,
    inputSchemaJson: {
      type: 'object',
      properties: {
        query: { type: 'string', description: 'Search query' },
        limit: { type: 'integer' },
        contextBudget: { type: 'integer' },
      },
      required: ['query'],
    },
  }));
}
