import { defineConfig } from 'vitest/config';
import { fileURLToPath } from 'url';
import path from 'path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  resolve: {
    alias: {
      '@iris/connector-sdk': path.resolve(__dirname, '../../packages/connector-sdk/src/index.ts'),
      '@iris/core/logger': path.resolve(__dirname, '../../packages/core/src/logger.ts'),
      '@iris/core/errors': path.resolve(__dirname, '../../packages/core/src/errors.ts'),
      '@iris/core': path.resolve(__dirname, '../../packages/core/src/index.ts'),
      '@iris/semantic-core/glossary': path.resolve(__dirname, '../../packages/semantic-core/src/glossary.ts'),
      '@iris/semantic-core/metrics': path.resolve(__dirname, '../../packages/semantic-core/src/metrics.ts'),
      '@iris/semantic-core/sync-events': path.resolve(__dirname, '../../packages/semantic-core/src/sync-events.ts'),
      '@iris/semantic-core/connector-health-service': path.resolve(__dirname, '../../packages/semantic-core/src/connector-health-service.ts'),
      '@iris/semantic-core/context-permissions': path.resolve(__dirname, '../../packages/semantic-core/src/context-permissions.ts'),
      '@iris/semantic-core/schema-discoverer': path.resolve(__dirname, '../../packages/semantic-core/src/schema-discoverer.ts'),
      '@iris/semantic-core/proactive-suggester': path.resolve(__dirname, '../../packages/semantic-core/src/proactive-suggester.ts'),
      '@iris/semantic-core/osi-exporter': path.resolve(__dirname, '../../packages/semantic-core/src/osi-exporter.ts'),
      '@iris/semantic-core/nlp-config-parser': path.resolve(__dirname, '../../packages/semantic-core/src/nlp-config-parser.ts'),
      '@iris/semantic-core/workflow-templates': path.resolve(__dirname, '../../packages/semantic-core/src/workflow-templates.ts'),
      '@iris/semantic-core/workflow-service': path.resolve(__dirname, '../../packages/semantic-core/src/workflow-service.ts'),
      '@iris/semantic-core/index-optimizer': path.resolve(__dirname, '../../packages/semantic-core/src/index-optimizer.ts'),
      '@iris/semantic-core/benchmarking': path.resolve(__dirname, '../../packages/semantic-core/src/benchmarking.ts'),
      '@iris/semantic-core/connector-marketplace': path.resolve(__dirname, '../../packages/semantic-core/src/connector-marketplace.ts'),
      '@iris/semantic-core/embedding-provider': path.resolve(__dirname, '../../packages/semantic-core/src/embedding-provider.ts'),
      '@iris/semantic-core/reindex-utils': path.resolve(__dirname, '../../packages/semantic-core/src/reindex-utils.ts'),
      '@iris/semantic-core/vector-health': path.resolve(__dirname, '../../packages/semantic-core/src/vector-health.ts'),
      '@iris/semantic-core/data-lineage': path.resolve(__dirname, '../../packages/semantic-core/src/data-lineage.ts'),
      '@iris/semantic-core/data-import-export': path.resolve(__dirname, '../../packages/semantic-core/src/data-import-export.ts'),
      '@iris/semantic-core/resource-builder': path.resolve(__dirname, '../../packages/semantic-core/src/resource-builder.ts'),
      '@iris/semantic-core/sync-quality-monitor': path.resolve(__dirname, '../../packages/semantic-core/src/sync-quality-monitor.ts'),
      '@iris/semantic-core/entity-deduplicator': path.resolve(__dirname, '../../packages/semantic-core/src/entity-deduplicator.ts'),
      '@iris/semantic-core/connector-cost-attribution': path.resolve(__dirname, '../../packages/semantic-core/src/connector-cost-attribution.ts'),
      '@iris/semantic-core/collaboration-manager': path.resolve(__dirname, '../../packages/semantic-core/src/collaboration-manager.ts'),
      '@iris/semantic-core/search-quality-evaluator': path.resolve(__dirname, '../../packages/semantic-core/src/search-quality-evaluator.ts'),
      '@iris/semantic-core/onboarding-manager': path.resolve(__dirname, '../../packages/semantic-core/src/onboarding-manager.ts'),
      '@iris/semantic-core/cost-optimizer': path.resolve(__dirname, '../../packages/semantic-core/src/cost-optimizer.ts'),
      '@iris/semantic-core/entity-validator': path.resolve(__dirname, '../../packages/semantic-core/src/entity-validator.ts'),
      '@iris/semantic-core/index-repair-service': path.resolve(__dirname, '../../packages/semantic-core/src/index-repair-service.ts'),
      '@iris/semantic-core/transformation-dsl': path.resolve(__dirname, '../../packages/semantic-core/src/transformation-dsl.ts'),
      '@iris/semantic-core/metrics-anomaly-detector': path.resolve(__dirname, '../../packages/semantic-core/src/metrics-anomaly-detector.ts'),
      '@iris/semantic-core': path.resolve(__dirname, '../../packages/semantic-core/src/index.ts'),
      '@iris/cache/response-cache': path.resolve(__dirname, '../../packages/cache/src/response-cache.ts'),
      '@iris/compression': path.resolve(__dirname, '../../packages/compression/src/index.ts'),
      '@iris/queue': path.resolve(__dirname, '../../packages/queue/src/sync-job-queue.ts'),
      '@iris/queue/connector-resilience': path.resolve(__dirname, '../../packages/queue/src/connector-resilience.ts'),
      '@iris/connector-hubspot/webhook-handler': path.resolve(__dirname, '../../packages/connectors/hubspot/src/webhook-handler.ts'),
      '@iris/connector-slack/webhook-handler': path.resolve(__dirname, '../../packages/connectors/slack/src/webhook-handler.ts'),
      '@iris/semantic-core/index-analytics': path.resolve(__dirname, '../../packages/semantic-core/src/index-analytics.ts'),
      '@iris/semantic-core/auto-tuning-optimizer': path.resolve(__dirname, '../../packages/semantic-core/src/auto-tuning-optimizer.ts'),
      '@iris/semantic-core/multi-provider-optimizer': path.resolve(__dirname, '../../packages/semantic-core/src/multi-provider-optimizer.ts'),
      '@iris/semantic-core/provider-registry': path.resolve(__dirname, '../../packages/semantic-core/src/providers/provider-registry.ts'),
      '@iris/semantic-core/compliance-reporter': path.resolve(__dirname, '../../packages/semantic-core/src/compliance-reporter.ts'),
      '@iris/semantic-core/data-lineage': path.resolve(__dirname, '../../packages/semantic-core/src/data-lineage.ts'),
      '@iris/semantic-core/dedup-reconciliation': path.resolve(__dirname, '../../packages/semantic-core/src/dedup-reconciliation.ts'),
      '@iris/semantic-core/proactive-context-engine': path.resolve(__dirname, '../../packages/semantic-core/src/proactive-context-engine.ts'),
      '@iris/semantic-core/metric-formula-engine': path.resolve(__dirname, '../../packages/semantic-core/src/metric-formula-engine.ts'),
      '@iris/semantic-core/nlp-config-engine': path.resolve(__dirname, '../../packages/semantic-core/src/nlp-config-engine.ts'),
    },
  },
  test: {
    include: ['src/**/__tests__/**/*.test.ts', 'src/__tests__/**/*.test.ts'],
    exclude: ['**/*.integration.test.ts'],
  },
});
